#!/bin/bash -l
#PBS -l nodes=1:ppn=4:gtx1080,walltime=18:59:00
#PBS -N cntkJobPChannels
#PBS -o cnktJobPC.out -e cntkJobPC.err

export LD_LIBRARY_PATH=~/cuDNN/cuda/lib64/
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/cntk/cntk/dependencies/lib/

module load cuda
module load openmpi/1.10.5-gcc

cd /home/hpc/capn/mppi027h/

cntk/cntk/bin/cntk  configFile=/home/woody/capn/mppi027h/km3net/Configs/3dPChannelConReg.cntk 